name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  cloud_firestore: any
  firebase_core: any
  firebase_auth: any
  flutter_hooks: any
  hooks_riverpod: any
  get: 4.6.6
  url_launcher: 6.2.5
  flutter_slidable: 3.1.0
  google_fonts: 6.2.1
  get_time_ago: 1.3.1
  logger: 2.2.0
  provider: 6.1.2
  flutter_riverpod: 2.5.1
  location: ^5.0.3
  camera: 0.10.5+9
  geocoding: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_app_name: ^0.1.0
  flutter_test: 
    sdk: flutter

flutter_app_name: 
  name: Wallet App

flutter: 
  assets: 
    - images/
    - assets/images/
  uses-material-design: true

