name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  cloud_firestore: any
  firebase_core: any
  firebase_auth: any
  flutter_hooks: any
  get: 4.6.6
  url_launcher: ^6.2.6
  flutter_slidable: 3.1.0
  google_fonts: 6.2.1
  get_time_ago: 1.3.1
  logger: ^2.3.0
  provider: ^6.1.2
  flutter_riverpod: 2.5.1
  location: ^6.0.1
  camera: ^0.11.0
  geocoding: 3.0.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  fluttertoast: 8.2.5
  lottie: ^3.1.2
  intl: 0.19.0
  quickalert: 1.1.0
  pinput: ^4.0.0
  country_picker: ^2.0.26
  firebase_storage: any
  shared_preferences: 2.2.3
  image_picker: ^1.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_app_name: ^0.1.0
  flutter_test: 
    sdk: flutter

flutter_app_name: 
  name: Wallet App

flutter: 
  assets: 
    - images/
    - assets/images/
  uses-material-design: true

