name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  cloud_firestore: any
  firebase_core: any
  firebase_auth: any
  firebase_messaging: any
  flutter_hooks: any
  get: 4.6.6
  path_provider: any
  url_launcher: ^6.2.6
  flutter_slidable: ^3.1.1
  google_fonts: 6.2.1
  get_time_ago: ^2.0.0
  logger: ^2.3.0
  provider: ^6.1.2
  flutter_riverpod: any
  location: any
  camera: any
  geocoding: any
  qr_flutter: any
  like_button: any
  flutter_barcode_scanner: ^2.0.0
  fluttertoast: any
  flutter_image_slider: any
  lottie: any
  intl: 0.19.0
  quickalert: 1.1.0
  pinput: ^5.0.0
  country_picker: ^2.0.26
  firebase_storage: any
  shared_preferences: any
  fancy_password_field: any
  image_picker: any
  flutter_local_notifications: ^8.2.0
  getwidget: 4.0.0
  open_file: ^3.5.6
  pdf: ^3.8.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: any
  flutter_app_name: ^0.1.0
  flutter_test: 
    sdk: flutter

flutter_app_name: 
  name: Wallet App

flutter_icons: 
  image_path: assets/icons/icon.png/
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - images/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/Open_Sans/
  uses-material-design: true

