// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrCnNpPOmoBX33MTBkCPvjP5qQ1D73OUA',
    appId: '1:90474389965:web:0fae8b7a08d67655182484',
    messagingSenderId: '90474389965',
    projectId: 'myapp-97691',
    authDomain: 'myapp-97691.firebaseapp.com',
    storageBucket: 'myapp-97691.appspot.com',
    measurementId: 'G-HB8RP8E1SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHX1nCcY98JganQZhfbxutkCyXXjPkzM',
    appId: '1:90474389965:android:6830013d1ba5fc03182484',
    messagingSenderId: '90474389965',
    projectId: 'myapp-97691',
    storageBucket: 'myapp-97691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB719BfWTclsK-E-iYueL1dTgCdbD8Jcqk',
    appId: '1:90474389965:ios:64dd2f982234a5dd182484',
    messagingSenderId: '90474389965',
    projectId: 'myapp-97691',
    storageBucket: 'myapp-97691.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB719BfWTclsK-E-iYueL1dTgCdbD8Jcqk',
    appId: '1:90474389965:ios:64dd2f982234a5dd182484',
    messagingSenderId: '90474389965',
    projectId: 'myapp-97691',
    storageBucket: 'myapp-97691.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrCnNpPOmoBX33MTBkCPvjP5qQ1D73OUA',
    appId: '1:90474389965:web:2c733198f22ad92b182484',
    messagingSenderId: '90474389965',
    projectId: 'myapp-97691',
    authDomain: 'myapp-97691.firebaseapp.com',
    storageBucket: 'myapp-97691.appspot.com',
    measurementId: 'G-9K0ZVQBG8F',
  );

}